name: GorgonEditor
version: 0.0.1
description: A sample web application
dependencies:
  archive: '>=1.0.18 <2.0.0'
  browser: '>=0.10.0+2 <0.11.0'
  duengine:
    git: https://github.com/cantidio/duEngine
  gorgon: '>=0.14.0 <0.15.0'
  http_server: any
  polymer: '>=0.15.1 <0.16.0'
dev_dependencies:
  unittest: '>=0.11.0+2 <0.12.0'
transformers:
- polymer